### ISSUE TITLE
Mis-parsing changelog for html5lib

### ISSUE THREAD

**Issue by danni** [pyupio/safety-db#1764]
html5lib has done something whacky with their changelogs, but it's causing havoc with safety because it things the version number is all one version and said version doesn't exist.

https://pyup.io/changelogs/html5lib/

https://github.com/html5lib/html5lib-python/blob/master/CHANGES.rst

**Comment by jayfk** [comment]
Thanks for reporting @danni, I'll look into it.

**Comment by jayfk** [comment]
Fixed in https://github.com/pyupio/safety-db/pull/1770
