### ISSUE TITLE
Windows compat?

### ISSUE THREAD

**Issue by AndreLouisCaron** [pyupio/safety-db#2249]
Thanks for posting this tool, looks very promising!

I just tried this on Windows and I got an error:
```
  safety\formatter.py", line 27, in get_terminal_size
    rows, columns = subprocess.check_output(['stty', 'size']).split()
WindowsError: [Error 2] Le fichier spécifié est introuvable
```

I guess the `stty` command is not available on Windows.  There is an API to get this information.  Would you be willing to accept a patch to fix this?

Thanks!

**Comment by jayfk** [comment]
Hey @AndreLouisCaron!

Thanks for raising this issue. I've tried to make this as compatible as possible,  looks like I've missed something.

The code is here: https://github.com/pyupio/safety/blob/master/safety/formatter.py#L12-L34

I'd be super happy to review a patch that fixes this :).

**Comment by AndreLouisCaron** [comment]
OK, seems like the fix might be simple.  From what I see, the code catches `FileNotFoundError`, but the exception raised on Python 2.7 is `WindowsError` (a subclass of `OSError`).  I just made a local change in my installed copy and I get the safety report.

Pull request should be coming in soon :-)

**Comment by AndreLouisCaron** [comment]
Seems like I reported this on the wrong project.  Will close this one and re-open under `pyupio/safety`.
