### ISSUE TITLE
html5lib dual numbering

### ISSUE THREAD

**Issue by stephenpaulger** [pyupio/safety-db#2251]
I assume whilst trying to mitigate some of the issues of the _unique_ version numbering used by html5lib they have started giving each version two version numbers for each release.

https://pypi.python.org/pypi/html5lib

0.9999999 (seven 9s) is the same software as 1.0b8.

```
% echo "html5lib==0.9999999" | safety check --stdin
stty: stdin isn't a terminal
safety report
---
-> html5lib, installed 0.9999999, affected <0.99999999, id 25846
```
We should see the same vulnerability for 1.0b8

```
% echo "html5lib==1.0b8" | safety check --stdin
stty: stdin isn't a terminal
safety report
---
No known security vulnerabilities found.
```

**Comment by jayfk** [comment]
Thanks!

**Comment by jayfk** [comment]
Fixed that. Should be in the next update :).

**Comment by stephenpaulger** [comment]
Fantastic, thank you.
