### ISSUE TITLE
Typosquatting packages from vulnerability skcsirt-sa-20170909-pypi

### ISSUE THREAD

**Issue by Lucas-C** [pyupio/safety-db#2254]
Could you please include in `safety-db` the following malicious packages,
crafted for typosquatting:
```
acqusition
apidev-coop
bzip
crypt
django-server
pwd
setup-tools
telnet
urlib3
urllib
```

Source: http://www.nbu.gov.sk/skcsirt-sa-20170909-pypi/

**Comment by jayfk** [comment]
On it!

**Comment by jayfk** [comment]
Thanks, added them a couple days ago: https://github.com/pyupio/safety-db/commit/b8a9d943c7ccc6624be87d0cc9b9e5970fbd83a9

**Comment by Lucas-C** [comment]
Thank you !
