### ISSUE TITLE
Django 1.11.9 / 2.0.1

### ISSUE THREAD

**Issue by dbrgn** [pyupio/safety-db#2259]
Two patch releases were published:

https://www.djangoproject.com/weblog/2018/feb/01/security-releases/

**Comment by jayfk** [comment]
Yes, thanks!

It looks like the monthly update was prior to that. I have, however, just pushed a massive update that also included both Django patch releases in an out of band update.

https://github.com/pyupio/safety-db/blob/master/data/insecure.json#L313

If in doubt, you can alwas check the corresponding page on pyup.io, e.g. for Django: https://pyup.io/changelogs/django/

If the package is listed as insecure, the following update to Safety DB will include the update.

**Comment by dbrgn** [comment]
Ah, I wasn't aware that this repo isn't the authoritative source :slightly_smiling_face:
