### ISSUE TITLE
Post database submissions here?

### ISSUE THREAD

**Issue by edrolo-paulm** [pyupio/safety-db#2262]
Are submissions to this database from the public allowed to made, and if so, is this GH issues page the place to do it?

I noticed an [important security bulletin](https://docs.newrelic.com/docs/using-new-relic/new-relic-security/security-bulletins/security-bulletin-nr18-07) was released by New Relic for their Python agent only a couple of weeks ago and I'd like to make that available in your vuln database.

**Comment by jayfk** [comment]
Is this about the fix introduced in `2.106.1.88` for https://docs.newrelic.com/docs/using-new-relic/new-relic-security/security-bulletins/security-bulletin-nr18-07?

This is already tracked on pyup.io here: https://pyup.io/changelogs/newrelic/

Submissions are more than welcome! The main database is on pyup.io, this one here is updated once a month based on it. If you submit a PR here, I'm going to merge it right away tough.

I'm going to close this issue and create a new one about how to contribute.
