### ISSUE TITLE
June 2019 update included no changes

### ISSUE THREAD

**Issue by rback123** [pyupio/safety-db#2279]
The June updates didn't make any changes to the underlying database files, which doesn't seem correct. Could someone please verify the update process is functioning as intended?

### Commits in question
1. https://github.com/pyupio/safety-db/commit/f8985b0bf870d713858fee8a5cdc7ccb71d97020 
1. https://github.com/pyupio/safety-db/commit/5f65819e28fc324aba41b44f997cebb75fb846c7

### Commit Histories
1. `insecure.json` = https://github.com/pyupio/safety-db/commits/master/data/insecure.json
1. `insecure_full.json` = https://github.com/pyupio/safety-db/commits/master/data/insecure_full.json

**Comment by rback123** [comment]
The July 2019 updates also didn't make any changes to the underlying database files. Does that mean this project is no longer being maintained?

**Comment by Jwomers** [comment]
Hi!

Sorry this was a mistake in our systems. The updates will be working again
any day now and will retroactively go out this week!

Justin

**Comment by MartinFalatic** [comment]
I don't see any progress on this - and today Pyup.io is experiencing widespread 500 errors on the site, and the paid DB is inaccessible.

What's going on?

**Comment by rback123** [comment]
The files were updated in the August 2019 update. Thanks for resolving this!

I’m marking this as closed.
