### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by leblancfg** [pyupio/safety-db#2280]
I have a use case where using your PyPI package would be oodles better than to download `insecure.json` from github. In your documentation, the expected installation method is through `pip install`, but:
1. per #2273 that use case is broken
2. the latest version is more than a year old

Updating the PyPI package would fix those two issues.

Should you so choose, you can then automate the PyPI package update on a monthly basis for one of your Travis runs.

**Comment by maaaaz** [comment]
I'm adding here that aside the packaging issues, the main script cannot work as the relative `data` folder is not known after a pip install : https://github.com/pyupio/safety-db/blob/4398cda0934fc1fdc8f359bdafef92cc8ace9f6e/safety_db.py#L13

**Comment by rafaelpivato** [comment]
This should get fixed with next release this week.
