### ISSUE TITLE
invalid pip vuln marks all pip packages as vuln

### ISSUE THREAD

**Issue by thehesiod** [pyupio/safety-db#2286]
https://pyup.io/api/v1/safety/insecure_full.json is returning:
```json
  "pip": [
    "<1.4",
    "<6.0",
    "<6.1.0",
    "<1.3",
    "<1.3",
    "",
    "<1.5"
  ],
```
The empty string value causes pip to always be reported as vulnerable

**Comment by harlekeyn** [comment]
Thanks. Fixed.

**Comment by thehesiod** [comment]
still failing

**Comment by harlekeyn** [comment]
Please try again and let me know if it is still happening.

**Comment by thehesiod** [comment]
still failing

**Comment by 780Farva** [comment]
This looks resolved to me now when I hit that endpoint. @thehesiod can you confirm?

**Comment by thehesiod** [comment]
yep

**Comment by 780Farva** [comment]
Nice. This unblocks pypa/pipenv#4147
