### ISSUE TITLE
Invalid python-gnupg version reported in pipenv security check

### ISSUE THREAD

**Issue by yyang-nasuni** [pyupio/safety-db#2288]
### Issue description

Starting from today (3/17), the `pipenv check` is reporting following vulnerability based on security check info in the db. But the reported `python-gnupg` version is invalid and also both pip lib & gpg executable are up-to-date. 

Could someone please check the DB being used by pipenv for this `python-gnupg` lib? It was working fine as of yesterday and there was no change in our app code or pipenv setup. Please see more pipenv details in the original issue reported in pipenv repo here (https://github.com/pypa/pipenv/issues/4156).

```bash
# install latest python-gnupg package (version 0.4.5)
# https://pypi.org/project/python-gnupg/
$ pipenv install python-gnupg

# pipenv check was working fine as of 3/16/2020 and starts to reporting following error on 3/17/2020
$ pipenv check
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
37367: python-gnupg <2.2.12 resolved (0.4.5 installed)!
Python-gnupg 2.2.12 - [dirmngr] Avoid possible CSRF attacks via http redirects.  A HTTP query will not anymore follow a 3xx redirect unless the Location header gives the same host.  If the host is different only the host and port is taken from the Location header and the original path and query parts are kept.

```
The required `2.2.12` version is invalid for the python package and looks like reference to actual `gpg` executable version, which is already satisfied on the machine.
```bash
$ gpg --version
gpg (GnuPG) 2.2.19
```

**Comment by harlekeyn** [comment]
Thanks for reporting this. I have updated the DB and marked to vulnerability as not valid.

It could take some time for the cache to update as well.

**Comment by yyang-nasuni** [comment]
Thanks for prompt fix. It is all set now.
