### ISSUE TITLE
Reporting wrong package

### ISSUE THREAD

**Issue by stsewd** [pyupio/safety-db#2291]
Hi, I'm not sure if this is the correct place to report this. Pyup is reporting we have a vulnerable package (commonmark) https://pyup.io/repos/github/readthedocs/readthedocs.org/commits/?page=1#e23183aa128e563b367d84f8010b4f67d6b0835e

But we are using the latest version of commonmark. I dig a little and turns out the bot is reporting the version from the npm package, not from the one in pypi

https://github.com/commonmark/commonmark.js/blob/98c25ab583dd6dcc4d350c7779a0fe0f09e0a221/changelog.txt#L216-L217

**Comment by harlekeyn** [comment]
Duplicate of #2292

**Comment by stsewd** [comment]
This is fixed now, thanks
