### ISSUE TITLE
Wrong package - Monero

### ISSUE THREAD

**Issue by ladislavdubravsky** [pyupio/safety-db#2300]
* safety, version 1.8.5
* Python 3.7.5
* operating system: Ubuntu 18.04

### Description

Starting today, `safety check` suddenly reports
```
╞════════════════════════════╤═══════════╤══════════════════════════╤══════════╡
│ package                    │ installed │ affected                 │ ID       │
╞════════════════════════════╧═══════════╧══════════════════════════╧══════════╡
│ monero                     │ 0.7.1     │ <0.10.0                  │ 37447    │
│ monero                     │ 0.7.1     │ <0.12.0.0                │ 37446    │
│ monero                     │ 0.7.1     │ <0.9.1                   │ 37448    │
╘══════════════════════════════════════════════════════════════════════════════╛
```

however, it mistakes [this package](https://pypi.org/project/monero) with something else -- the package I use has no newer version than 0.7.1.

**Comment by harlekeyn** [comment]
Fixed.
Cause: [monero-project](https://github.com/monero-project) was confused with [monero-ecosystem](https://github.com/monero-ecosystem).
