### ISSUE TITLE
Safety wants impossible version for python-nomad

### ISSUE THREAD

**Issue by threemachines** [pyupio/safety-db#2303]
Hi – 
Y'all have a record of a vuln in the python-nomad library:
https://github.com/pyupio/safety-db/blob/cada380e3835ede4dce629bbf489017a5f080c3d/data/insecure_full.json#L11472-L11482

Problem is, there _is_ no 2.20.0 version of python-nomad; the most recent release is [1.2.1](https://github.com/jrxFive/python-nomad/releases/tag/1.2.1).

It looks like y'all might have picked up [the changelog of the 1.0.1 release](https://github.com/jrxFive/python-nomad/releases/tag/1.0.1), which was updating the `requests` library to 2.20.0 (!) for the exact issue described in your advisory, and somehow transposed that onto python-nomad?

**Comment by harlekeyn** [comment]
Thanks. Fixed.
Note that this fix will reflect immediately in the live DB of Safety, but not in the free version until that gets updated on May 1st, 2020.
