### ISSUE TITLE
Wrong spec in Django advisory

### ISSUE THREAD

**Issue by sbs2001** [pyupio/safety-db#2307]
Check  https://github.com/pyupio/safety-db/blob/9cb84541a691044512dab8422dc2a36383e0fff3/data/insecure_full.json#L3098  

This is from https://pypi.org/project/Django/#history ![django history](http://imgur.com/fg4ch67l.png)

As you can see `1.8` > `1.8c1` , but the spec contains `">=1.8,<1.8c1"`(which translates to English as 'any version which is greater than `1.8` but less than `1.8c1` is vulnerable ) which basically no version will satisfy. 

Please make the necessary corrections

**Comment by harlekeyn** [comment]
Thanks Shivam. Good catch.
I've now changed it to `>=1.8a1,<1.8c1`.

Note that this will not update in the free vulnerabilities database until June 1st.

**Comment by sbs2001** [comment]
Fixed by June update
