### ISSUE TITLE
python-semantic-release finding

### ISSUE THREAD

**Issue by wyardley** [pyupio/safety-db#2315]
Is there a place to lookup the ID in the report?

I see that the August updates added this finding:
```
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| python-semantic-release    | 7.2.1     | <15.13.25                | 37516    |
+==============================================================================+
```

There is not a 15.x release of python-semantic-release. Do you have more details about the vulnerability that's supposed to be at issue here?

**Comment by wyardley** [comment]
Just based on the version number, I'm guessing this may be a mixup with the Node semantic-release package (https://github.com/semantic-release/semantic-release) vs https://github.com/relekang/python-semantic-release/

**Comment by harlekeyn** [comment]
You are 100% right @wyardley. I have now removed the vulnerability from our database.

**Comment by wyardley** [comment]
@harlekeyn: will this show up in the next monthly update? Or when will it roll out of the db?

**Comment by harlekeyn** [comment]
Hello @wyardley,

It was removed instantly from our proprietary database. Users of our free database will see the change on September 1st.

Tristan
