### ISSUE TITLE
Under-described Django issue 38650

### ISSUE THREAD

**Issue by l0b0** [pyupio/safety-db#2317]
The current description:

> The :setting:SECURE_REFERRER_POLICY setting in Django 3.1 defaults to 'same-origin'. With this configured, :class:~django.middleware.security.SecurityMiddleware sets the :ref:referrer-policy header to same-origin on all responses that do not already have it. This prevents the Referer header being sent to other origins. If you need the previous behavior, explicitly set :setting:SECURE_REFERRER_POLICY to None.

This does not mention a CVE or any external ticket system, so it's difficult to find more information about it.

**Comment by MartinFalatic** [comment]
We're seeing that as well. It sounds like a warning about 3.1 configs, yet this paints all versions < 3.1 as vulnerable. I'm inclined to say this is not relevant to Django < 3.1, and it's not clear to me how you'd resolve this in 3.1 in a way that would clear this warning.

**Comment by harlekeyn** [comment]
Thanks for bringing this to our attention. We have now removed this from our database of vulnerabilities.
