### ISSUE TITLE
Should malicious libraries also be included in safety-db?

### ISSUE THREAD

**Issue by exhuma** [pyupio/safety-db#2319]
I came across [an article mentioning malicious libraries](https://www.zdnet.com/article/two-malicious-python-libraries-removed-from-pypi/). Right now, I can see neither of those two libraries in the safety-db (unless I missed it). It would be beneficial if those reports would also be included in the safety-db.

Was it not included by design, because these libraries are by themselves malicious, or is this just "not yet included", in which case a PR might solve this.

**Comment by harlekeyn** [comment]
Thank you @exhuma! They were not yet included, but we have now added them to our database. Paid users should see this update immediately, and free users will see it in the database update on September 1st, 2020.
