### ISSUE TITLE
gender-guesser marked as blocker, but not in insecure_full.json

### ISSUE THREAD

**Issue by 0LL13** [pyupio/safety-db#2321]
In my project https://pyup.io/account/repos/github/0LL13/person/ the package
gender-guesser
is marked as Python blocker, however, it is not listed in insecure_full.json

**Comment by harlekeyn** [comment]
Hello Oliver,

The packages gender-guesser does not have Python 3 support. That is why it shows up as such on your PyUp dashboard. It does not have a known vulnerability, and that is why it is not included in _insecure_full.json_.

Tristan

**Comment by 0LL13** [comment]
This is the travis build record for gender-guesser:

https://travis-ci.org/github/lead-ratings/gender-guesser/jobs/183323476

It says Python 3.5
I do not understand why you say gender-guesser has not Python 3 support.

**Comment by harlekeyn** [comment]
Yes, you are right. 

Here's what's going on: the data that we base this flag on comes from PyPi. 

I have just changed the value, though this will not show up in the free version of Safety until October 1st, 2020. Also, it may change back once Gender-guesser releases an update.

I am very sorry. This is all I can do.

**Comment by 0LL13** [comment]
Thanks anyway.
