### ISSUE TITLE
DOC/Question: What is the relationship between safety-db and NVD (National Vulnerability Database)?

### ISSUE THREAD

**Issue by MartinThoma** [pyupio/safety-db#2322]
I've seen NVD being mentioned in some issues:

* https://github.com/pyupio/safety-db/issues/2294
* https://github.com/pyupio/safety-db/issues/2290
* https://github.com/pyupio/safety-db/issues/2276

What is the relationship between safety-db and NVD?

**Comment by harlekeyn** [comment]
Hello Martin,

We use their public data. That's the only relationship we have with them.

Tristan

**Comment by MartinThoma** [comment]
Ah, cool! So is this an automatic ingestion of the NVD data or is this a manual process? Does the safety-db contain additional data or is it only a subset of NVD? (Or maybe exactly NVD)?

**Comment by harlekeyn** [comment]
When a python-related CVE appears in the NVD data, we get notified by our software.

CVEs only make up 21% of the vulnerabilities in our database. The other 79% are vulnerabilities that we find by looking at the changelogs of all Python packages on PyPi.org (around 260 thousand at the moment).

Both processes are partly automated and partly manual. We assess every vulnerability that we find before it gets added to our database.

Our paying customers use our real-time database to scan their Python dependencies. Our free users get access to our free database, which only gets updated once a month.

We have various tools that users can use to scan their Python dependencies against these databases.

**Comment by MartinThoma** [comment]
Thank you very much for the feedback. I appreciate it :-)
