### ISSUE TITLE
Invalid value for `cve` at insecure_full.json

### ISSUE THREAD

**Issue by sbs2001** [pyupio/safety-db#2323]
https://github.com/pyupio/safety-db/blob/c4f4673861c540659b8995cf23af2915c584e9d3/data/insecure_full.json#L2640 

The value for cve there should probably be `null` .

**Comment by harlekeyn** [comment]
Thanks, fixed.
Note that this would not update to our free database until October 1st.

**Comment by sbs2001** [comment]
FYI we have code/tests to detect such issues https://github.com/nexB/vulnerablecode/blob/e65ac68177dd41eaae9a79914712bac00058e0aa/vulnerabilities/importers/safety_db.py#L51

If you are interested I could file a PR to include a schema test as a part of CI.

**Comment by harlekeyn** [comment]
Thanks for that link. We're actually about to include some server-side code that will sanitize the CVE value on our end.

Please keep in mind that `Or(None, Regex(r"CVE-\d+-\d+"))` will return `None` if there are multiple CVE values.
