### ISSUE TITLE
lambda-warmer-py warning references a nonexistent version

### ISSUE THREAD

**Issue by jeffcasavant** [pyupio/safety-db#2331]
`lambda-warmer-py` is marked as insecure before [version 1.2.0](https://github.com/pyupio/safety-db/blob/4b13e366e5d5f17bc69d8ae6a0eadd2818d3380e/data/insecure_full.json#L10206), but it's only at [version 0.6](https://pypi.org/project/lambda-warmer-py/#history).

Was the name reused, or is this just a mistake?

**Comment by harlekeyn** [comment]
You are right. We had it associated with https://github.com/jeremydaly/lambda-warmer by accident. Thanks for the note.

Note that users who use our free software will not see this correction until April 1st, 2021.
