### ISSUE TITLE
Package `dash` has no version 2.2.0

### ISSUE THREAD

**Issue by alexcjohnson** [pyupio/safety-db#2336]
`PVE-2021-40962` says "Dash 2.2.0 includes a security fix." but there's no Dash 2.0 yet, let alone 2.2

As discussed in https://github.com/plotly/dash/issues/1695 this may just need to change to Dash 1.21.0:

> The only thing I can think of that this might have been based on is plotly.js 2.2.1 https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md#221----2021-07-06 which includes an XSS patch and is included in Dash 1.21 https://github.com/plotly/dash/blob/dev/CHANGELOG.md#updated

**Comment by yeisonvargasf** [comment]
Hi @alexcjohnson, it was a False positive and it was marked as not valid. Thanks for report this.

**Comment by alexcjohnson** [comment]
Thanks @yeisonvargasf for the quick attention.
