### ISSUE TITLE
Package `tensorflow < 2.7` incorrectly listed as vulnerable for all versions

### ISSUE THREAD

**Issue by bswami50** [pyupio/safety-db#2342]
Fixes for 2 issues (pyup.io-42098 and pyup.io-42062) which are flagged as vulnerabilities <2.7 in November update are ported to patch branches for previous versions.

See: 
* https://github.com/tensorflow/tensorflow/blob/db5546e1a8920c4e1e635f79575d6b2329001f04/tensorflow/security/advisory/tfsa-2021-167.md ["We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4"] and [patch](https://github.com/tensorflow/tensorflow/commit/64918868e2154b06c7479347a59a4230f785e9fa).
* https://github.com/tensorflow/tensorflow/blob/9f0b3c6802e314bb7a17f4ff20807bdbbc0f5187/tensorflow/security/advisory/tfsa-2021-152.md ["We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4"]

Can you consider removing the entry for tensorflow < 2.7 and modify it to reflect the patched versions in the database? We are on tensorflow 2.4 and this is failing our CI builds.

**Comment by mihaimaruseac** [comment]
Note that 2.3 and 2.4 are EOL'ed, they won't receive any more patches

**Comment by SCH227** [comment]
@bswami50 we just updated it in our db. Check if it's correct now. 
Sorry for the inconvenience and thank you for informing us!
