### ISSUE TITLE
sendgrid vulnerability should have lower limit

### ISSUE THREAD

**Issue by m-aciek** [pyupio/safety-db#2344]
December update added a vulnerability for sendgrid.

```
+============================+===========+==========================+==========+
| package                    | installed | affected                 | ID       |
+============================+===========+==========================+==========+
| sendgrid                   | 5.6.0     | <6.9.1                   | 42721    |
+==============================================================================+
| Sendgrid 6.9.1 updates its dependency minimum 'starbank-ecdsa' to v2.0.1 to  |
| include a security fix.                                                      |
+==============================================================================+
```

`starkbank-ecdsa` was introduced as a dependency in 6.4.1 [1] version of sendgrid, therefore `affected` value should be `>=6.4.1,<6.9.1`.

For apps that use sendgrid<6.4.1 safety is currently signaling a false positive.

[1] It was added as a dependency in setup.py for 6.4.1 version:
* https://github.com/sendgrid/sendgrid-python/commit/443ee00d046ef59b7fdacc9493f5b5de6cbe1d84
* for 6.4.0 it was added to requirements used for tests, but missed in setup.py: https://github.com/hellno/sendgrid-python/commit/cb58667142e30642b9b60318b834c0713c71ac12#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552

**Comment by SCH227** [comment]
We just corrected the spec in our db. Thank you a lot for the report!
