### ISSUE TITLE
Wrong version identifier in vulnerabilities pyup.io-34226 & pyup.io-49495

### ISSUE THREAD

**Issue by sephii** [pyupio/safety-db#2356]
Vulnerabilities [PVE-2022-49495](https://pyup.io/vulnerabilities/PVE-2022-49495/49495/) and [PVE-2021-34226](https://pyup.io/vulnerabilities/PVE-2021-34226/34226/) list DjangoCMS version ">=3.4.0.<3.4.3" as being vulnerable. This specifier set is invalid and causes any DjangoCMS version to match against it:

```
>>> from packaging.specifiers import SpecifierSet
>>> from packaging.version import Version
>>> Version("3.4.0") in SpecifierSet(">=3.4.0.<3.4.3")
True
>>> Version("3.9.0") in SpecifierSet(">=3.4.0.<3.4.3")
True
```

I don’t know what pyupio uses internally for version comparison, but I think the syntax should be ">=3.4.0,<3.4.3":

```
>>> from packaging.specifiers import SpecifierSet
>>> from packaging.version import Version
>>> Version("3.4.0") in SpecifierSet(">=3.4.0,<3.4.3")
True
>>> Version("3.9.0") in SpecifierSet(">=3.4.0,<3.4.3")
False
```

**Comment by SCH227** [comment]
@sephii, thank you for reaching out with this issue! We already fixed the entries in our DB
