### ISSUE TITLE
dparse v0.6.1 showing as im

### ISSUE THREAD

**Issue by Mr-McBride** [pyupio/safety-db#2357]
I upgraded dparse to version v0.6.1, but it is still  showing up in safety scans and advising that I need to upgrade to a version newer than v0.5.2. (ID 50571).

**Comment by SCH227** [comment]
Good day! How are you?
I just checked the vulnerability 50571 data, and it seems ok. 
Would you like to provide more information about how you perform the scans? For example, the commands you are using, Safety version...

**Comment by SCH227** [comment]
Closing this one. Feel free to re-open it if you have something more to add!
