### ISSUE TITLE
insecure-package is  no longer returned as vulnerable

### ISSUE THREAD

**Issue by awsbillz** [pyupio/safety-db#2364]
Hi safety-db,

Recently, we discovered that `insecure-package` is no longer returned as a vulnerable package in the `insecure.json` from both the free version and the paid version. 

Is this new behavior expected? If this is expected, how do we test new `safety` installations?

**Comment by harlekeyn** [comment]
Hi Bill,

Thank you for bringing this to our attention. Indeed, the vulnerability you referred to was temporarily omitted from our database. We appreciate your vigilance in this matter.

We have promptly reinstated this vulnerability and it should be visible again in your scans by tomorrow.

For those following this discussion, "insecure-package" is not a genuine package but rather a placeholder created exclusively for testing Safety's functionality. Despite its name, it poses no risk.

Once again, thank you for your diligent reporting. Your active involvement aids in maintaining the accuracy and integrity of our vulnerability database.

Tristan
