### ISSUE TITLE
safety scan results in Unhandled exception happened: Invalid specifier: '<.0.13.4' - for package requests

### ISSUE THREAD

**Issue by sbxmichaelm** [pyupio/safety-db#2372]
The db apparently contains this as the list of vulnerable packages for `requests`

['>=2.1,<=2.5.3',
 '<=2.19.1',
 '<2.3.0',
 '<2.32.2',
 '>=2.3.0,<2.31.0',
 '<.0.13.4']

but `<.0.13.4` is not a valid version specifier

**Comment by benglewis** [comment]
@jayfk This is pretty bad...

**Comment by sbxmichaelm** [comment]
Looks like this was fixed, safety scans are no longer failing
